fix Grouped laboratory tests by patient
openmrs/openmrs-esm-laboratory-app pull request #82
Opened 2024-07-31 16:11 UTC by FelixKiprotich350

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
 Grouped laboratory tests by patient (displaying Patient name and order count) and all the test details on expanding

## Screenshots
[laborders.webm](https://github.com/user-attachments/assets/182ccb46-42e9-4e16-9584-24a357144d90)

## Related Issue

## Other

2024-07-31 16:12 UTC, FelixKiprotich350 commented
@donaldkibet , @ojwanganto kindly have a look

2024-07-31 17:53 UTC, ojwanganto commented on src/lab-tabs/data-table-extensions/completed-lab-requests-table.extension.tsx
> +          // { actionName: "labResultsForm", displayPosition: 0 },
we can remove the comments

2024-07-31 17:55 UTC, ojwanganto commented
@FelixKiprotich350 - kindly create a ticket and update in the ticket.

2024-07-31 17:56 UTC, FelixKiprotich350 commented
Yea sure this is a community repo I'll do that

On Wed, Jul 31, 2024, 8:55 PM ojwanganto ***@***.***> wrote:

> @FelixKiprotich350 <https://github.com/FelixKiprotich350> - kindly create
> a ticket and update in the ticket.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openmrs/openmrs-esm-laboratory-app/pull/82#issuecomment-2261056816>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARGPKMCELFI7PPKAS6WTNRDZPEQJLAVCNFSM6AAAAABLYZV6T2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENRRGA2TMOBRGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-02 04:57 UTC, donaldkibet requested changes
Thanks @FelixKiprotich350
@ojwanganto should we go with these designs https://app.zeplin.io/project/6650717a9275db731847fb32/screen/66589826434fe1b75fd2c459

2024-08-02 04:57 UTC, donaldkibet commented on src/components/orders-table/listOrderDetails.component.tsx
> +// can render orders of a patient
```suggestion

```

2024-08-02 04:57 UTC, donaldkibet commented on src/components/orders-table/listOrderDetails.component.tsx
> +const ListOrderDetails: React.FC<ListOrdersDetailsProps> = (props) => {
Since we already have the types for the props, we should just destructure it e.g `({ actions })`

2024-08-02 04:57 UTC, donaldkibet commented on src/components/orders-table/orders-data-table.component.tsx
> +  }, [props.excludeColumns, t]);
Please fix this hooks dependency error

2024-08-02 04:57 UTC, donaldkibet commented on src/types.ts
> +  displayPosition: 0 | number;
```suggestion
  order: 0 | number;
```

2024-08-02 05:11 UTC, FelixKiprotich350 commented on src/lab-tabs/data-table-extensions/completed-lab-requests-table.extension.tsx
> +          // { actionName: "labResultsForm", displayPosition: 0 },
done

2024-08-02 10:18 UTC, donaldkibet approved these changes

2024-08-02 12:46 UTC, ojwanganto commented
Thanks, @FelixKiprotich350

2024-08-02 12:46 UTC, merged