Add french translation
openmrs/openmrs-esm-laboratory-app pull request #93
Opened 2024-10-01 14:48 UTC by azizdiakite

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
https://openmrs.atlassian.net/browse/O3-4041

## Screenshots

## Related Issue

## Other

2024-10-06 07:31 UTC, reagan-meant approved these changes
LGTM. Thanks @azizdiakite

2024-10-16 20:09 UTC, denniskigen requested changes

2024-10-16 20:09 UTC, denniskigen commented on translations/fr.json
> +  "itemsPerPage": "Éléments par page"
Thank you for working on this, @azizdiakite! So, we don't modify non-`en` translation files by hand. Instead, we use the Transifex integration for that. These strings ought to be translated via the Transifex UI. Automated PRs will then provide the updated strings back to the repo ([similar to this one](https://github.com/openmrs/openmrs-esm-laboratory-app/pull/98)).

Read more about this [here](https://om.rs/translate).

2024-10-16 20:09 UTC, denniskigen commented on src/index.ts
>      slot: 'laboratory-dashboard-slot',
This is the canonical way to translate the dashboard link text:

```suggestion
  // t('laboratory', 'Laboratory')
  createHomeDashboardLink({
    name: 'laboratory',
    slot: 'laboratory-dashboard-slot',
    title: 'Laboratory'
```

2024-10-16 20:09 UTC, denniskigen commented on src/components/create-dashboard-link.component.tsx
> +      {t(title, 'Laboratory')}
```suggestion
      {t(title)}
```

2024-10-22 18:29 UTC, closed without merging